on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: updating the repo
      run: git submodule update --init --recursive 
    - name: chown
      run: sudo chown 1450 /tmp && sudo chmod a=rwx /tmp
    - name: Build and push to Docker Hub
      path: ./galaxy
      dockerfile: galaxy/Dockerfile
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.docker_registry_username }}
        password: ${{ secrets.docker_registry_password }}
        repository: bedroesb/galaxy-stable
        tags: latest